#!/usr/bin/env bash
# Distributes the consolidated root .env (the one shared with developers and
# collaborators over a secure channel) into each service's own per-directory
# .env file. Each service only ever reads its own .env — this script is the
# one-time (or "whenever the shared .env changes") step that keeps all of
# them in sync with a single source of truth.
#
# ── How to run it ────────────────────────────────────────────────────────
#   1. Get the shared .env from whoever sent it to you (secure channel only —
#      it contains live database/API credentials).
#   2. Save it as .env at the repository root (same directory as this
#      script). It's gitignored — never commit it.
#   3. Run:            ./sync-env.sh
#      or:             make sync-env
#   4. Re-run any time the root .env changes. Existing per-service .env
#      files are backed up to <file>.bak.<timestamp> before being
#      overwritten, so nothing is silently lost.
#   5. Then run `make setup` to verify every venv/node_modules is installed,
#      and `make up` to start the stack.
#
# OPENAI_API_KEY is synced separately after writing service settings, without
# printing it. Only the root .env is used; shell keys are ignored.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

SRC="$ROOT/.env"
if [ ! -f "$SRC" ]; then
  echo "No .env found at $SRC" >&2
  echo "Place the shared root .env here first (see README.md), then re-run this script." >&2
  exit 1
fi

MISSING=0

get() {
  grep -E "^${1}=" "$SRC" 2>/dev/null | tail -1 | cut -d= -f2- | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

require() {
  local key="$1"
  local val
  val="$(get "$key")"
  if [ -z "$val" ]; then
    echo "  ⚠ missing/empty in root .env: $key" >&2
    MISSING=1
  fi
  printf '%s' "$val"
}

backup_if_exists() {
  local target="$1"
  if [ -f "$target" ]; then
    local stamp
    stamp="$(date +%Y%m%d%H%M%S)"
    cp "$target" "${target}.bak.${stamp}"
    echo "  backed up existing $(basename "$target") -> $(basename "$target").bak.${stamp}"
  fi
}

write_file() {
  # write_file <target-path> <one-line description> KEY=value KEY=value ...
  local target="$1"
  local description="$2"
  shift 2
  backup_if_exists "$target"
  mkdir -p "$(dirname "$target")"
  {
    echo "# Generated by sync-env.sh from the root .env on $(date -u +%Y-%m-%dT%H:%M:%SZ) UTC."
    echo "# Do not edit directly — edit the root .env and re-run ./sync-env.sh."
    echo "# $description"
    for kv in "$@"; do
      echo "$kv"
    done
  } > "$target"
  echo "  wrote $target"
}

echo "Distributing $SRC into each service's .env ..."

echo
echo "mathbank-db/.env"
write_file "mathbank-db/.env" "Local PostgreSQL 16 cluster." \
  "EXTERNAL_DB_ROOT=$(require EXTERNAL_DB_ROOT)" \
  "PG_SUPERUSER=$(require PG_SUPERUSER)" \
  "PG_SUPERUSER_PASSWORD=$(require PG_SUPERUSER_PASSWORD)" \
  "APP_DB=$(require APP_DB)" \
  "APP_USER=$(require APP_USER)" \
  "APP_DB_PASSWORD=$(require APP_DB_PASSWORD)" \
  "PG_PORT=$(require PG_PORT)"

echo
echo "mathbank-graph/.env"
write_file "mathbank-graph/.env" "Local Neo4j Community server." \
  "EXTERNAL_DB_ROOT=$(require EXTERNAL_DB_ROOT)" \
  "NEO4J_PASSWORD=$(require NEO4J_PASSWORD)" \
  "NEO4J_BOLT_PORT=$(require NEO4J_BOLT_PORT)" \
  "NEO4J_HTTP_PORT=$(require NEO4J_HTTP_PORT)" \
  "PG_PORT=$(require PG_PORT)" \
  "APP_DB=$(require APP_DB)" \
  "APP_USER=$(require APP_USER)" \
  "APP_DB_PASSWORD=$(require APP_DB_PASSWORD)"

echo
echo "mathbank-graph/remote.env"
write_file "mathbank-graph/remote.env" "Remote Neon Postgres + Neo4j AuraDB (used by every *-remote make target)." \
  "NEON_PG_HOST=$(require NEON_PG_HOST)" \
  "NEON_PG_PORT=$(require NEON_PG_PORT)" \
  "NEON_PG_DATABASE=$(require NEON_PG_DATABASE)" \
  "NEON_PG_USER=$(require NEON_PG_USER)" \
  "NEON_PG_PASSWORD=$(require NEON_PG_PASSWORD)" \
  "NEON_PG_SSLMODE=$(require NEON_PG_SSLMODE)" \
  "NEON_PG_CHANNEL_BINDING=$(require NEON_PG_CHANNEL_BINDING)" \
  "NEO4J_URI=$(require NEO4J_URI)" \
  "NEO4J_USERNAME=$(require NEO4J_USERNAME)" \
  "NEO4J_PASSWORD=$(require NEO4J_PASSWORD_AURA)" \
  "NEO4J_DATABASE=$(require NEO4J_DATABASE)" \
  "AURA_INSTANCEID=$(require AURA_INSTANCEID)" \
  "AURA_INSTANCENAME=$(require AURA_INSTANCENAME)"

echo
echo "mathbank-rest/.env"
write_file "mathbank-rest/.env" "FastAPI service — points at the remote Neon/AuraDB stack." \
  "POSTGRES_HOST=$(require POSTGRES_HOST)" \
  "POSTGRES_PORT=$(require POSTGRES_PORT)" \
  "POSTGRES_DB=$(require POSTGRES_DB)" \
  "POSTGRES_USER=$(require POSTGRES_USER)" \
  "POSTGRES_PASSWORD=$(require POSTGRES_PASSWORD)" \
  "POSTGRES_SSLMODE=$(require POSTGRES_SSLMODE)" \
  "NEO4J_URI=$(require NEO4J_URI)" \
  "NEO4J_USER=$(require NEO4J_USER)" \
  "NEO4J_PASSWORD=$(require NEO4J_PASSWORD_AURA)" \
  "JWT_SECRET=$(require JWT_SECRET)" \
  "ADMIN_API_KEY=$(require ADMIN_API_KEY)"

echo
echo "mathbank-agent/.env"
write_file "mathbank-agent/.env" "Google ADK agentic backend." \
  "POSTGRES_HOST=$(require POSTGRES_HOST)" \
  "POSTGRES_PORT=$(require POSTGRES_PORT)" \
  "POSTGRES_DB=$(require POSTGRES_DB)" \
  "POSTGRES_USER=$(require POSTGRES_USER)" \
  "POSTGRES_PASSWORD=$(require POSTGRES_PASSWORD)" \
  "POSTGRES_SSLMODE=$(require POSTGRES_SSLMODE)" \
  "MATHBANK_AGENT_MODEL=$(require MATHBANK_AGENT_MODEL)" \
  "MATHBANK_REST_BASE_URL=$(require MATHBANK_REST_BASE_URL)" \
  "MATHBANK_AGENT_DEFAULT_ROLE=$(require MATHBANK_AGENT_DEFAULT_ROLE)"

echo
echo "mathbank-web/.env"
write_file "mathbank-web/.env" "Next.js app — server-side only, the browser never sees these." \
  "MATHBANK_AGENT_BASE_URL=$(require MATHBANK_AGENT_BASE_URL)" \
  "NEO4J_URI=$(require NEO4J_URI)" \
  "NEO4J_USER=$(require NEO4J_USER)" \
  "NEO4J_PASSWORD=$(require NEO4J_PASSWORD_AURA)" \
  "MATHBANK_REST_BASE_URL=$(require MATHBANK_REST_BASE_URL)" \
  "MATHBANK_ADMIN_API_KEY=$(require MATHBANK_ADMIN_API_KEY)" \
  "ADMIN_LOGIN_USERNAME=$(require ADMIN_LOGIN_USERNAME)" \
  "ADMIN_LOGIN_PASSWORD=$(require ADMIN_LOGIN_PASSWORD)" \
  "ADMIN_SESSION_SECRET=$(require ADMIN_SESSION_SECRET)"

echo
if [ "$MISSING" -eq 1 ]; then
  echo "⚠ One or more keys were missing/empty in the root .env (see warnings above)." >&2
  echo "  The per-service .env files were still written — fix the root .env and re-run." >&2
  exit 1
fi

if ! node scripts/sync-openai-key.mjs; then
  exit 1
fi
echo "Done. Every service .env is now in sync with the root .env."
